### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by gggauravgandhi** [vimal1083/handwritten-character-recognition#1]
I am getting following error, please can you help ?

![image](https://user-images.githubusercontent.com/13112509/30770896-996014e6-a059-11e7-9114-bbf65e866741.png)

**Comment by vimal1083** [comment]
@gggauravgandhi  Have you given the correct dataset location

> DATASET_LOCATION = '/var/www/python/ML/hcr/English/Hnd/Img'
