### ISSUE TITLE
Code Run problem

### ISSUE THREAD

**Issue by shahriar4041** [vimal1083/handwritten-character-recognition#4]
After opening jupyter which files i should run ? I already changed the dataset path and generate dataset.should i run both parse_form.py and tf_handwrtiien_character_detector.py.I have already run generate_dataset.py and it runs successfully.When i run parse_form.py from terminal it shows following error 
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 9748
Traceback (most recent call last):
  File "parse_form.py", line 26, in <module>
    create_binary_image(FORM_PATH)
  File "parse_form.py", line 17, in create_binary_image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.error: /io/opencv/modules/imgproc/src/color.cpp:9748: error: (-215) scn == 3 || scn == 4 in function cvtColor

I am pretty sure that FORM_PATH = '/home/handwrittingrecognition/Desktop/hand/lead_creation_form.jpg' this line returns the error.I could not able to locate the lead_creation_form.jpg' file.should i expect it to generate or gather from some other source.

I am pretty much new in the scenario and if you describe the further process in details also the expected output it will be a great help.

Thanks in advance.

**Comment by vimal1083** [comment]
I have created this project to read characters written by the user in the paper. Also, I had designed the form with a black border which would help me to crop the image programmatically. `parse_form.py` is the python file automatically crop the image inside the black border(there is no ML here).  So I request you to just ignore this and concentrate on the notebook.

So after installing dependencies just run the notebook with correct dataset path.
