### ISSUE TITLE
error in running

### ISSUE THREAD

**Issue by kaleesMsl** [vimal1083/handwritten-character-recognition#9]
sir please provide the detailed decription to run the 
tf_handwrtiien_character_detector.py
ie. where i have to change the iinput image path
please share your output screen shots for reference

**Comment by vimal1083** [comment]
Hi @kaleesMsl ,

Kindy refer here https://github.com/vimal1083/handwritten-character-recognition/blob/master/Hand_writing_Recog_Simple_Linear_Model.ipynb

**Comment by kaleesMsl** [comment]
thank u sir
